- data/risks/networks/1/bb-a-usdauraautostaker.json
> feat(risk): add bb-a-usd aura auto staker group

- data/meta/vaults/250/0x03B82e4070cA32FF63A03F2EcfC16c0165689a9d.json
- data/meta/vaults/250/0x0446acaB3e0242fCf33Aa526f1c95a88068d5042.json
- data/meta/vaults/250/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0.json
- data/meta/vaults/250/0x0fBbf9848D969776a5Eb842EdAfAf29ef4467698.json
- data/meta/vaults/250/0x148c05caf1Bb09B5670f00D511718f733C54bC4c.json
- data/meta/vaults/250/0x1b48641D8251c3E84ecbe3f2bD76B3701401906D.json
- data/meta/vaults/250/0x1e2fe8074a5ce1Bb7394856B0C618E75D823B93b.json
- data/meta/vaults/250/0x2C850cceD00ce2b14AA9D658b7Cad5dF659493Db.json
- data/meta/vaults/250/0x357ca46da26E1EefC195287ce9D838A6D5023ef3.json
- data/meta/vaults/250/0x637eC617c86D24E421328e6CAEa1d92114892439.json
- data/meta/vaults/250/0xA97E7dA01C7047D6a65f894c99bE8c832227a8BC.json
- data/meta/vaults/250/0xCbCaF8cB8cbeAFA927ECEE0c5C56560F83E9B7D9.json
- data/meta/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/meta/vaults/250/0xD3c19eB022CAC706c898D60d756bf1535d605e1d.json
- data/meta/vaults/250/0xEF0210eB96c7EB36AF8ed1c20306462764935607.json
- data/meta/vaults/250/0xF137D22d7B23eeB1950B3e19d1f578c053ed9715.json
- data/meta/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
- data/meta/vaults/250/0xf2d323621785A066E64282d2B407eAc79cC04966.json
- Allow zap-in and zap-out transactions on Fantom vaults
> feat: enable zaps on Fantom vaults

- data/meta/vaults/1/0x1025b1641d1F23C289412Dd5E5701e9810103a93.json
- data/meta/vaults/1/0x2e5c7e9B1Da0D9Cb2832eBb06241d18552A85400.json
- data/meta/vaults/1/0x3B27F92C0e212C671EA351827EDF93DB27cc0c65.json
- data/meta/vaults/1/0x6B5ce31AF687a671a804d8070Ddda99Cab926dfE.json
- data/meta/vaults/1/0xE5eDcE53e39Cbc6d819E2C340BCF295e0084ff7c.json
- yvusdt 4.3
- yvaud-usdc
- yvchf-usdc
- yvgbp-usdc
- yveur-usdc
> chore: drop new on those with apys

- data/risks/networks/1/maker-lev.json
> feat(risk): Change testingScore from 3 -> 2

- data/meta/protocols/10/Aave.json
- data/meta/protocols/10/MakerDAO.json
- data/meta/strategies/10/AaveFlashloanFolding.json
- data/meta/strategies/10/AaveIronbankLenderOptimizer.json
- data/meta/vaults/10/0x0a2f234Ad2e5e9047067904A9D37D0Cd02b80D12.json
- data/meta/vaults/10/0x0fBeA11f39be912096cEc5cE22F46908B5375c19.json
- data/meta/vaults/10/0x4C8b1958B09B3bde714f68864Bcc3a74Eaf1A23D.json
- data/meta/vaults/10/0xA628c54C850ff1077b5C954491D19EccE7e321fF.json
- data/meta/vaults/10/0xC328D83883F5F90E1108D4Dd7A18FFcA17Ae74d7.json
- data/meta/vaults/10/0xfbef713696465DDab297164c3b6A0122D92A3bAc.json
- aave v3 flashloan folding
- aave v3 protocol
- update aave lender
- makerdao protocol opti
> add(meta): new optimism strategies & protocols

- internal/utils/helpers/constants.go
- Add lp-yCRV and st-yCRV previous deployments
- Add comment for why it's blacklisted
> feat: update blacklist vaults and add reason

- data/meta/vaults/1/0x4213458C69c19E6792510E1153cb0c5834665fdC.json
- data/meta/vaults/1/0xc5F3D11580c41cD07104e9AF154Fc6428bb93c73.json
- Replaces old Balancer Boosted Aave USD Pool vault with new one
> feat: replace Balancer Boosted Aave USD Pool vault

- data/meta/vaults/1/0x27B5739e22ad9033bcBf192059122d163b60349D.json
- data/meta/vaults/1/0xc97232527B62eFb0D8ed38CF3EA103A6CcA4037e.json
- Remove `new` tag for st-ycrv and lp-ycrv vaults
> feat: release ycrv vaults apy

- data/meta/vaults/1/0x16825039dfe2a5b01F3E1E6a2BBF9a576c6F95c4.json
- Curve d3pool is no longer receiving CRV rewards as gauge has been killed.
> feat: delist curve d3pool

- data/meta/_config/schema/vault.json
- data/meta/vaults/1/0x27B5739e22ad9033bcBf192059122d163b60349D.json
- data/meta/vaults/1/0x8a0889d47f9Aa0Fac1cC718ba34E26b867437880.json
- data/meta/vaults/1/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a.json
- data/meta/vaults/1/0xA696a63cc78DfFa1a63E9E50587C197387FF6C7E.json
- data/meta/vaults/1/0xa258C4606Ca8206D8aA700cE2143D7db854D168c.json
- data/meta/vaults/1/0xa9fE4601811213c340e850ea305481afF02f5b28.json
- data/meta/vaults/1/0xc5bDdf9843308380375a611c18B50Fb9341f502A.json
- data/meta/vaults/1/0xcB550A6D4C8e3517A939BC79d0c7093eb7cF56B5.json
- data/meta/vaults/10/0x0a2f234Ad2e5e9047067904A9D37D0Cd02b80D12.json
- data/meta/vaults/10/0xA628c54C850ff1077b5C954491D19EccE7e321fF.json
- data/meta/vaults/250/0x03B82e4070cA32FF63A03F2EcfC16c0165689a9d.json
- data/meta/vaults/250/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0.json
- data/meta/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/meta/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
- Add classification for Specials
- Add classification for Currency
- Add classification for Smart Contract Platform
> feat: add classification for the remaining vaults

- data/meta/vaults/1/0x1A5ebfF0E881Aec34837845e4D0EB430a1B4b737.json
- data/meta/vaults/1/0x321d570790fd2f109Fe4e55aa419Adf2fce0c842.json
- data/meta/vaults/1/0x4CbB6A5EC00cEEC252a7091559484F7adb83165f.json
- data/meta/vaults/1/0x5b2384D566D2E4a0b29B8eccB642C63199cd393c.json
- data/meta/vaults/1/0x6f0Ace0F94f4B9890Dfa99A4175B3Ef0288C16B3.json
- data/meta/vaults/1/0x75A291F0232ADD37d72Dd1Dcff55B715755ECDEe.json
- data/meta/vaults/1/0x8078198Fc424986ae89Ce4a910Fc109587b6aBF3.json
- data/meta/vaults/1/0x82c83ddA32DB09F63F9A59A129278f3fdC3EeE67.json
- data/meta/vaults/1/0x8cdf57760Be305F32e03B3d231e5A81e550C6295.json
- data/meta/vaults/1/0xAd86Df2e8F989c828B25A7Da5EB1Ec363283fA3F.json
- data/meta/vaults/1/0xB5dE7250128775a317B3f775a7AFcEC73571B732.json
- data/meta/vaults/1/0xD347e7A3DdF5Ce4C42E19a4F30eEAA761795C72B.json
- data/meta/vaults/1/0xF614d3864EF53510909a94c618a5EC1Ff75103BF.json
- data/meta/vaults/1/0xa540744DEDBDA9eF64cf753F0E851EfE4a419EA9.json
- data/meta/vaults/1/0xa8E0c42F45C877e611C76F2D4bF57476f2014381.json
- data/meta/vaults/1/0xb37094c1B5614Bd6EcE40AFb295C26F4377069d3.json
- data/meta/vaults/1/0xe5F625e8f4D2A038AE9583Da254945285E5a77a4.json
> update(meta): new factory apy

- data/meta/strategies/10/AaveIronbankLenderOptimizer.json
- data/meta/strategies/10/AaveOptimizer.json
- remove deprecated lender ironbank
> fix(strategy): opti genlender

- data/meta/tokens/1/0xaA17A236F2bAdc98DDc0Cf999AbB47D47Fc0A6Cf.json
- data/meta/vaults/1/0x132d8D2C76Db3812403431fAcB00F3453Fc42125.json
> refactor: aETHc -> ankrETH

- data/risks/networks/1/lp-ycrv.json
- data/risks/networks/1/st-ycrv.json
- add lp-ycrv 
- fix st-ycrv
closes #250 
fixes #249
> feat(risk): updates and fixes

- data/risks/networks/1/compound-v3-lender-borrower.json
- data/risks/networks/1/st-ybal.json
> feat(risk): st-ybal & new comp v3

- data/risks/networks/10/stakingrewards.json
- add optimism staking rewards to risk framework
> feat(risk): add op staking rewards

- data/meta/tokens/8453.json
Updated names for strategies that use Yearn Morpho Vaults
> chore: update morpho yearn names

- data/meta/vaults/1.json
- data/meta/vaults/137.json
- data/meta/vaults/42161.json
- data/meta/vaults/8453.json
retire PT vaults and migrate strategies
> chore: retire old vaults

- data/meta/vaults/1.json
- update sky compounder description and risk score
- update sky compounder migration target and contract
- update retirement notice for old strategies.
> chore: update meta and migration info

- data/meta/vaults/146.json
Updates sonic vault metadata to hide test vault and add usdc.e-2 vault to featured.
> chore: update Sonic vaults metadata

- common/env/chain.katana.go
- common/ethereum/blocktime.go
disregard [d25fd27](https://github.com/yearn/ydaemon/pull/508/commits/d25fd279cb5c0b9904526b7f973deae4b3f63495). [f6cf36f](https://github.com/yearn/ydaemon/pull/508/commits/f6cf36fdd4bd018d0c634ae06adc8942744e89bf) fixes some upgrades that were missed here https://github.com/yearn/ydaemon/commit/bc640c00fbe6673388860d039d8078aae267d931
> Fix negative Katana apys

- data/meta/vaults/8453.json
adds True Yield Dollar to the fancy filter per Spalen's request
> chore: add true yield dollar to fancy

- external/vaults/models.go
- external/vaults/route.vaults.one.go
- internal/fetcher/strategies.go
Remove estimated apr optimization for "inactive" strategies
> The best optimization is no optimization
